- name: variables at task level
  hosts: localhost
  # these variables of parent or play level
  vars:
  - money: "Rs.100000"
    Land: "100 Acres"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "Money: {{money}}. Land: {{Land}}"  
  - name: inherit values from play and override
    vars: 
    - money: "200000"
      houses: "4 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}. LAND: {{Land}}, HOUSES :{{houses}}"  